name: Test and Build (All Platforms)

on:
  workflow_dispatch:
  push:

env:
  TESTGAME_DIR: .github/workflows/testgame

jobs:
  build_and_test:
    strategy:
      matrix:
        runner:
          - ubuntu-22.04
          - windows-2022
          - macos-12
      fail-fast: false
    uses: ./.github/workflows/test-and-build-for-one-platform.yml
    with:
      runner: ${{ matrix.runner }}
